// require('./isUnique');
// require('./factorial');
// require('./addTwoArray');
// require('./isPrime');
// require('./balancedParentheses');
// require('./longestSubString');
// require('./midChar');
// require('./betterParseInt');
// require('./flatten');
// require('./anagramPalindrome');
// require('./eliminateDuplicates');
// require('./areTheySame');
// require('./sortArrays');
require('./letterChange');
